CREATE TABLE {table_name}
(
  HOUSE_ID VARCHAR PRIMARY KEY,
  TITLE VARCHAR,
  GUARANTEE_INFO VARCHAR,
  LINK VARCHAR NOT NULL UNIQUE,
  AREA VARCHAR,
  HOUSE_TYPE VARCHAR,
  FLOOR_INFO VARCHAR,
  BUILD_TIME_INFO INTEGER,
  BROKER_NAME VARCHAR,
  ADDRESS VARCHAR,
  LOCATE_A VARCHAR,
  LOCATE_B VARCHAR,
  TAGS VARCHAR,
  PRICE INTEGER,
  UNIT_PRICE INTEGER,
  GET_TIME VARCHAR,

  UNIQUE (HOUSE_ID)
)